import React, { useState } from "react";
import { useAppContext } from "@/context/AppContext";
import { useWebSocketContext } from "@/context/WebSocketContext";
import {
  Activity, CheckCircle2, ShieldAlert, Zap, Server,
  BarChart, FileText, Link as LinkIcon, Wifi, WifiOff,
  Loader2, Search, Send, FileCode, Database, FileJson,
  X, Plus
} from "lucide-react";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Slider } from "@/components/ui/slider";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";

// â”€â”€ Agent mode: multi-file tabs â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

interface FileTab {
  id: string;
  name: string;
  icon: React.ElementType;
  iconColor: string;
  content: React.ReactNode;
}

const FILE_TABS: FileTab[] = [
  {
    id: "analysis",
    name: "analysis.py",
    icon: FileCode,
    iconColor: "text-blue-400",
    content: (
      <div className="font-mono text-xs leading-relaxed text-slate-300 p-3">
        {([
          ["1",  <><span className="text-purple-400">import</span><span className="text-slate-300"> pandas </span><span className="text-purple-400">as</span><span className="text-slate-300"> pd</span></>],
          ["2",  <><span className="text-purple-400">import</span><span className="text-slate-300"> numpy </span><span className="text-purple-400">as</span><span className="text-slate-300"> np</span></>],
          ["3",  null],
          ["4",  <><span className="text-blue-400">def</span><span className="text-yellow-200"> process_data</span><span className="text-slate-400">(file_path: str):</span></>],
          ["5",  <><span className="pl-4 text-slate-500"># Generated by DataAgent v1.2</span></>],
          ["6",  <><span className="pl-4 text-slate-300">df = pd.read_csv(file_path)</span></>],
          ["7",  <><span className="pl-4 text-slate-300">df = df.dropna()</span></>],
          ["8",  <><span className="pl-4 text-purple-400">return</span><span className="text-slate-300"> df.describe()</span></>],
          ["9",  null],
          ["10", <><span className="text-blue-400">def</span><span className="text-yellow-200"> detect_anomalies</span><span className="text-slate-400">(df):</span></>],
          ["11", <><span className="pl-4 text-slate-300">{"z = np.abs((df - df.mean()) / df.std())"}</span></>],
          ["12", <><span className="pl-4 text-purple-400">return</span><span className="text-slate-300">{" df[(z < 3).all(axis=1)]"}</span></>],
        ] as [string, React.ReactNode][]).map(([num, content]) => (
          <div key={num} className="flex hover:bg-slate-900/30">
            <div className="w-7 text-slate-700 select-none text-right pr-3 flex-shrink-0">{num}</div>
            <div className="flex-1">{content}</div>
          </div>
        ))}
      </div>
    ),
  },
  {
    id: "schema",
    name: "schema.sql",
    icon: Database,
    iconColor: "text-purple-400",
    content: (
      <div className="font-mono text-xs leading-relaxed p-3">
        {([
          ["1",  <><span className="text-blue-400">CREATE TABLE</span><span className="text-slate-300"> users (</span></>],
          ["2",  <><span className="pl-4 text-yellow-300">id</span><span className="text-slate-400">          UUID PRIMARY KEY,</span></>],
          ["3",  <><span className="pl-4 text-yellow-300">email</span><span className="text-slate-400">       TEXT UNIQUE NOT NULL,</span></>],
          ["4",  <><span className="pl-4 text-yellow-300">created_at</span><span className="text-slate-400">  TIMESTAMPTZ DEFAULT NOW()</span></>],
          ["5",  <><span className="text-slate-300">);</span></>],
          ["6",  null],
          ["7",  <><span className="text-blue-400">CREATE INDEX</span><span className="text-slate-300"> idx_users_email</span></>],
          ["8",  <><span className="text-blue-400">ON</span><span className="text-slate-300"> users(email);</span></>],
          ["9",  null],
          ["10", <><span className="text-slate-500">-- Agent: add partial index WHERE deleted_at IS NULL</span></>],
        ] as [string, React.ReactNode][]).map(([num, content]) => (
          <div key={num} className="flex hover:bg-slate-900/30">
            <div className="w-7 text-slate-700 select-none text-right pr-3 flex-shrink-0">{num}</div>
            <div className="flex-1">{content}</div>
          </div>
        ))}
      </div>
    ),
  },
  {
    id: "config",
    name: "config.json",
    icon: FileJson,
    iconColor: "text-yellow-400",
    content: (
      <div className="font-mono text-xs leading-relaxed p-3 text-slate-300">
        {([
          ["1",  <span className="text-slate-400">{"{"}</span>],
          ["2",  <><span className="pl-4 text-blue-300">"model"</span><span className="text-slate-400">: </span><span className="text-green-300">"gpt-4o"</span><span className="text-slate-400">,</span></>],
          ["3",  <><span className="pl-4 text-blue-300">"temperature"</span><span className="text-slate-400">: </span><span className="text-orange-300">0.7</span><span className="text-slate-400">,</span></>],
          ["4",  <><span className="pl-4 text-blue-300">"max_tokens"</span><span className="text-slate-400">: </span><span className="text-orange-300">4096</span><span className="text-slate-400">,</span></>],
          ["5",  <><span className="pl-4 text-blue-300">"daemon_port"</span><span className="text-slate-400">: </span><span className="text-orange-300">{localStorage.getItem("archon_daemon_port") || window.location.port === "3000" ? "8765" : window.location.port || "8765"}</span><span className="text-slate-400">,</span></>],
          ["6",  <><span className="pl-4 text-blue-300">"autopilot"</span><span className="text-slate-400">: </span><span className="text-purple-300">false</span></>],
          ["7",  <span className="text-slate-400">{"}"}</span>],
        ] as [string, React.ReactNode][]).map(([num, content]) => (
          <div key={num} className="flex hover:bg-slate-900/30">
            <div className="w-7 text-slate-700 select-none text-right pr-3 flex-shrink-0">{num}</div>
            <div className="flex-1">{content}</div>
          </div>
        ))}
      </div>
    ),
  },
  {
    id: "readme",
    name: "README.md",
    icon: FileText,
    iconColor: "text-slate-300",
    content: (
      <div className="p-3 font-mono text-xs space-y-3">
        <div className="text-slate-200 font-bold text-sm"># Project Analysis</div>
        <div className="text-slate-500">*Generated by ResearchAgent Â· 2024-01-15*</div>
        <div className="text-slate-400 leading-relaxed">
          This codebase implements a data pipeline with PostgreSQL backend. The agent detected
          <span className="text-yellow-400"> 3 N+1 query patterns</span> and
          <span className="text-red-400"> 1 missing index</span>.
        </div>
        <div className="space-y-1">
          <div className="text-slate-300 font-bold">## Recommendations</div>
          <div className="text-slate-400">Â· Add composite index on (user_id, created_at)</div>
          <div className="text-slate-400">Â· Batch load user records with SELECT IN</div>
          <div className="text-slate-400">Â· Enable pg_stat_statements extension</div>
        </div>
      </div>
    ),
  },
];

// â”€â”€ Council slider state (controlled, so values persist) â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
function CouncilPanel({ activeContextFiles, telemetry }: {
  activeContextFiles: string[];
  telemetry: { tokens: number; cost: number; latency: number };
}) {
  const [gpt4oTemp, setGpt4oTemp] = useState(70);
  const [claudeTemp, setClaudeTemp] = useState(40);
  const [geminiTemp, setGeminiTemp] = useState(55);

  return (
    <>
      <div className="p-4 border-b border-slate-800/60 flex-shrink-0">
        <h3 className="text-xs font-mono font-semibold tracking-wider text-slate-500 uppercase flex items-center gap-2">
          <BarChart className="w-3.5 h-3.5 text-orange-500" />
          Consensus Tracker
        </h3>
      </div>
      <ScrollArea className="flex-1 p-4">
        <div className="space-y-6">
          <div className="space-y-3">
            <h4 className="text-[10px] uppercase tracking-widest text-slate-500 font-mono">Agreement Matrix</h4>
            <div className="space-y-2">
              <div className="bg-slate-900/80 border border-slate-800 rounded p-3">
                <div className="flex items-center gap-2 text-xs font-mono mb-2">
                  <CheckCircle2 className="w-3.5 h-3.5 text-green-500" />
                  <span className="text-slate-200">Architecture Pattern</span>
                </div>
                <div className="text-[10px] text-slate-500 pl-5">2/3 models agree on monolith-first.</div>
              </div>
              <div className="bg-slate-900/80 border border-slate-800 rounded p-3">
                <div className="flex items-center gap-2 text-xs font-mono mb-2">
                  <CheckCircle2 className="w-3.5 h-3.5 text-green-500" />
                  <span className="text-slate-200">Database Choice</span>
                </div>
                <div className="text-[10px] text-slate-500 pl-5">3/3 agree on PostgreSQL + JSONB.</div>
              </div>
              <div className="bg-slate-900/80 border border-red-900/30 rounded p-3">
                <div className="flex items-center gap-2 text-xs font-mono mb-2">
                  <ShieldAlert className="w-3.5 h-3.5 text-red-500" />
                  <span className="text-red-200">Deployment Strategy</span>
                </div>
                <div className="text-[10px] text-slate-400 pl-5">Conflict: PaaS vs Kubernetes</div>
              </div>
            </div>
          </div>

          <div className="space-y-3">
            <h4 className="text-[10px] uppercase tracking-widest text-slate-500 font-mono">Model Parameters</h4>
            <div className="space-y-4">
              <div className="space-y-2">
                <div className="flex justify-between text-xs font-mono">
                  <span className="text-blue-300">GPT-4o</span>
                  <span className="text-orange-400">{(gpt4oTemp / 100).toFixed(2)}</span>
                </div>
                <Slider
                  value={[gpt4oTemp]}
                  onValueChange={([v]) => setGpt4oTemp(v)}
                  max={100} step={1}
                  className="[&_[role=slider]]:bg-blue-400"
                />
              </div>
              <div className="space-y-2">
                <div className="flex justify-between text-xs font-mono">
                  <span className="text-orange-300">Claude 3.5</span>
                  <span className="text-orange-400">{(claudeTemp / 100).toFixed(2)}</span>
                </div>
                <Slider
                  value={[claudeTemp]}
                  onValueChange={([v]) => setClaudeTemp(v)}
                  max={100} step={1}
                  className="[&_[role=slider]]:bg-orange-400"
                />
              </div>
              <div className="space-y-2">
                <div className="flex justify-between text-xs font-mono">
                  <span className="text-purple-300">Gemini 1.5</span>
                  <span className="text-orange-400">{(geminiTemp / 100).toFixed(2)}</span>
                </div>
                <Slider
                  value={[geminiTemp]}
                  onValueChange={([v]) => setGeminiTemp(v)}
                  max={100} step={1}
                  className="[&_[role=slider]]:bg-purple-400"
                />
              </div>
            </div>
          </div>
        </div>
      </ScrollArea>
    </>
  );
}

// â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

export default function RightSidebar() {
  const { mode, activeContextFiles } = useAppContext();
  const {
    connected, connecting, telemetry, citations, researchText,
    isStreaming, sendResearch,
  } = useWebSocketContext();

  const [researchQuery, setResearchQuery] = useState("");
  const [activeFileTab, setActiveFileTab] = useState("analysis");
  const [openTabs, setOpenTabs] = useState(["analysis", "schema"]);

  const handleResearchSend = () => {
    if (!researchQuery.trim() || isStreaming) return;
    sendResearch(researchQuery.trim());
    setResearchQuery("");
  };

  const closeTab = (id: string, e: React.MouseEvent) => {
    e.stopPropagation();
    const next = openTabs.filter((t) => t !== id);
    setOpenTabs(next);
    if (activeFileTab === id) setActiveFileTab(next[next.length - 1] ?? "");
  };

  const openTab = (id: string) => {
    if (!openTabs.includes(id)) setOpenTabs((prev) => [...prev, id]);
    setActiveFileTab(id);
  };

  const activeTabData = FILE_TABS.find((t) => t.id === activeFileTab);

  return (
    <div className="flex flex-col h-full bg-[#020817]/95">
      {/* Connection status bar */}
      <div className="px-4 py-2 border-b border-slate-800/60 flex items-center justify-between flex-shrink-0">
        <div className="flex items-center gap-2">
          {connected ? (
            <Wifi className="w-3 h-3 text-green-400" />
          ) : connecting ? (
            <Loader2 className="w-3 h-3 text-orange-400 animate-spin" />
          ) : (
            <WifiOff className="w-3 h-3 text-red-400" />
          )}
          <span className={cn("text-[10px] font-mono uppercase tracking-widest", {
            "text-green-400":  connected,
            "text-orange-400": !connected && connecting,
            "text-red-400":    !connected && !connecting,
          })}>
            {connected ? "Daemon Online" : connecting ? "Connecting..." : "Daemon Offline"}
          </span>
        </div>
      </div>

      {/* â”€â”€ Chat Inspector â”€â”€ */}
      {mode === "chat" && (
        <>
          <div className="p-4 border-b border-slate-800/60 flex-shrink-0">
            <h3 className="text-xs font-mono font-semibold tracking-wider text-slate-500 uppercase flex items-center gap-2">
              <Activity className="w-3.5 h-3.5 text-blue-500" />
              Telemetry
            </h3>
          </div>
          <ScrollArea className="flex-1 p-4">
            <div className="space-y-6">
              <div className="space-y-3">
                <h4 className="text-[10px] uppercase tracking-widest text-slate-500 font-mono">Session Metrics</h4>
                <div className="grid grid-cols-2 gap-2">
                  <div className="bg-slate-900/80 border border-slate-800 rounded p-3">
                    <div className="text-[10px] text-slate-500 font-mono mb-1">TOKENS</div>
                    <div className="text-lg font-mono text-cyan-400">
                      {telemetry.tokens > 0 ? `${(telemetry.tokens / 1000).toFixed(1)}k` : "42.8k"}
                    </div>
                  </div>
                  <div className="bg-slate-900/80 border border-slate-800 rounded p-3">
                    <div className="text-[10px] text-slate-500 font-mono mb-1">EST. COST</div>
                    <div className="text-lg font-mono text-emerald-400">
                      ${telemetry.cost > 0 ? telemetry.cost.toFixed(2) : "0.84"}
                    </div>
                  </div>
                </div>
              </div>
              <div className="space-y-3">
                <h4 className="text-[10px] uppercase tracking-widest text-slate-500 font-mono">Active Context</h4>
                <div className="space-y-2">
                  {activeContextFiles.length > 0 ? (
                    activeContextFiles.map((id) => (
                      <div key={id} className="flex items-center gap-2 text-xs font-mono text-slate-300 bg-slate-900/50 p-2 rounded border border-slate-800">
                        <FileText className="w-3 h-3 text-slate-500" />
                        {id}.md
                      </div>
                    ))
                  ) : (
                    <div className="text-xs text-slate-600 font-mono italic">No files in context</div>
                  )}
                </div>
              </div>
              <div className="space-y-3">
                <h4 className="text-[10px] uppercase tracking-widest text-slate-500 font-mono">Model Engine</h4>
                <div className="bg-slate-900/80 border border-slate-800 rounded p-3 flex flex-col gap-2">
                  <div className="flex justify-between items-center text-xs font-mono">
                    <span className="text-slate-400">Primary</span>
                    <span className="text-blue-400">GPT-4o</span>
                  </div>
                  <div className="flex justify-between items-center text-xs font-mono">
                    <span className="text-slate-400">Latency</span>
                    <span className="text-emerald-400">{telemetry.latency > 0 ? `${telemetry.latency}ms` : "84ms"}</span>
                  </div>
                </div>
              </div>
            </div>
          </ScrollArea>
        </>
      )}

      {/* â”€â”€ Council Consensus (controlled sliders) â”€â”€ */}
      {mode === "council" && (
        <CouncilPanel activeContextFiles={activeContextFiles} telemetry={telemetry} />
      )}

      {/* â”€â”€ Research Output â”€â”€ */}
      {mode === "research" && (
        <div className="flex flex-col flex-1 overflow-hidden">
          <div className="p-4 border-b border-slate-800/60 flex-shrink-0">
            <h3 className="text-xs font-mono font-semibold tracking-wider text-slate-500 uppercase flex items-center gap-2">
              <Search className="w-3.5 h-3.5 text-purple-500" />
              Research Output
            </h3>
          </div>
          <div className="p-3 border-b border-slate-800/60 bg-slate-900/20 flex-shrink-0">
            <div className="flex gap-2">
              <input
                type="text"
                value={researchQuery}
                onChange={(e) => setResearchQuery(e.target.value)}
                onKeyDown={(e) => e.key === "Enter" && handleResearchSend()}
                placeholder={connected ? "Research vector..." : "Daemon offline"}
                disabled={!connected || isStreaming}
                data-testid="input-research-query-sidebar"
                className="flex-1 bg-black border border-slate-800 rounded px-3 py-1.5 text-xs font-mono text-slate-200 placeholder:text-slate-700 focus:outline-none focus:border-purple-500/50 disabled:opacity-40"
              />
              <Button
                size="sm"
                onClick={handleResearchSend}
                disabled={!connected || isStreaming || !researchQuery.trim()}
                className="bg-purple-600 hover:bg-purple-500 text-white px-3 py-1 h-auto disabled:opacity-40"
              >
                {isStreaming ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <Send className="w-3.5 h-3.5" />}
              </Button>
            </div>
          </div>
          <ScrollArea className="flex-1 p-4">
            <div className="space-y-5">
              <div className="space-y-2">
                <h4 className="text-[10px] uppercase tracking-widest text-slate-500 font-mono flex items-center gap-2">
                  <Zap className="w-3 h-3 text-purple-400" />
                  Live Stream
                  {isStreaming && <span className="w-1.5 h-1.5 rounded-full bg-purple-500 animate-pulse" />}
                </h4>
                <div className="bg-slate-900/50 border border-slate-800 rounded p-3 max-h-40 overflow-hidden relative">
                  <pre className="text-xs font-mono text-slate-400 leading-relaxed whitespace-pre-wrap break-words">
                    {researchText || "Awaiting research directive..."}
                  </pre>
                  <div className="absolute bottom-0 left-0 right-0 h-10 bg-gradient-to-t from-slate-900/90 to-transparent pointer-events-none" />
                </div>
              </div>
              <div className="space-y-2">
                <h4 className="text-[10px] uppercase tracking-widest text-slate-500 font-mono">Citation Vault</h4>
                <div className="space-y-2">
                  {citations.length > 0 ? (
                    citations.map((c) => (
                      <a key={c.id} href={c.url} target="_blank" rel="noopener noreferrer"
                        className="block bg-slate-900/80 border border-slate-800 hover:border-purple-500/50 rounded p-2 transition-colors">
                        <div className="flex items-center gap-2 text-[10px] font-mono text-purple-400 mb-1">
                          <LinkIcon className="w-3 h-3" /> [{c.id}]
                        </div>
                        <div className="text-xs text-slate-300 line-clamp-1">{c.title}</div>
                      </a>
                    ))
                  ) : (
                    <>
                      <a href="#" className="block bg-slate-900/80 border border-slate-800 hover:border-purple-500/50 rounded p-2 transition-colors">
                        <div className="flex items-center gap-2 text-[10px] font-mono text-purple-400 mb-1">
                          <LinkIcon className="w-3 h-3" /> [1] arXiv:2401.1234
                        </div>
                        <div className="text-xs text-slate-300 line-clamp-1">Attention is All You Need Revisited</div>
                      </a>
                      <a href="#" className="block bg-slate-900/80 border border-slate-800 hover:border-purple-500/50 rounded p-2 transition-colors">
                        <div className="flex items-center gap-2 text-[10px] font-mono text-purple-400 mb-1">
                          <LinkIcon className="w-3 h-3" /> [2] GitHub
                        </div>
                        <div className="text-xs text-slate-300 line-clamp-1">google-deepmind/graphcast</div>
                      </a>
                    </>
                  )}
                </div>
              </div>
            </div>
          </ScrollArea>
        </div>
      )}

      {/* â”€â”€ Agent File Inspector (tabbed) â”€â”€ */}
      {mode === "agents" && (
        <div className="flex flex-col flex-1 overflow-hidden">
          <div className="px-3 py-2 border-b border-slate-800/60 flex-shrink-0 flex items-center justify-between">
            <div className="flex items-center gap-2">
              <Server className="w-3.5 h-3.5 text-green-500" />
              <span className="text-xs font-mono font-semibold tracking-wider text-slate-500 uppercase">File Inspector</span>
            </div>
            <div className="relative group">
              <button className="w-5 h-5 flex items-center justify-center text-slate-600 hover:text-slate-300 transition-colors">
                <Plus className="w-3.5 h-3.5" />
              </button>
              <div className="absolute right-0 top-6 z-30 hidden group-hover:block w-36 bg-slate-900 border border-slate-800 rounded shadow-xl overflow-hidden">
                {FILE_TABS.filter((f) => !openTabs.includes(f.id)).map((f) => (
                  <button
                    key={f.id}
                    onClick={() => openTab(f.id)}
                    className="w-full flex items-center gap-2 px-3 py-2 text-xs font-mono text-slate-400 hover:bg-slate-800 hover:text-slate-200 transition-colors"
                  >
                    <f.icon className={cn("w-3 h-3 flex-shrink-0", f.iconColor)} />
                    {f.name}
                  </button>
                ))}
              </div>
            </div>
          </div>

          {/* Tab strip */}
          <div className="flex border-b border-slate-800/60 bg-[#010710] overflow-x-auto flex-shrink-0" style={{ scrollbarWidth: "none" }}>
            {openTabs.map((tabId) => {
              const tab = FILE_TABS.find((t) => t.id === tabId);
              if (!tab) return null;
              const active = activeFileTab === tabId;
              return (
                <div
                  key={tabId}
                  onClick={() => setActiveFileTab(tabId)}
                  className={cn(
                    "flex items-center gap-1.5 px-3 py-2 cursor-pointer border-r border-slate-800/60 flex-shrink-0 group transition-colors",
                    active
                      ? "bg-[#020817] border-b-2 border-b-green-500"
                      : "text-slate-600 hover:text-slate-400 hover:bg-slate-900/40"
                  )}
                >
                  <tab.icon className={cn("w-3 h-3 flex-shrink-0", active ? tab.iconColor : "text-slate-600")} />
                  <span className={cn("text-[10px] font-mono", active ? "text-slate-300" : "text-slate-600")}>{tab.name}</span>
                  <button
                    onClick={(e) => closeTab(tabId, e)}
                    className="ml-1 opacity-0 group-hover:opacity-100 text-slate-600 hover:text-slate-300 transition-all"
                  >
                    <X className="w-2.5 h-2.5" />
                  </button>
                </div>
              );
            })}
          </div>

          {/* File content */}
          <div className="flex-1 overflow-hidden bg-[#0d1117] relative">
            <div className="absolute top-2 right-2 z-10 text-[9px] font-mono text-slate-700 bg-[#0d1117] px-1">
              READ-ONLY
            </div>
            {openTabs.length === 0 ? (
              <div className="flex items-center justify-center h-full text-slate-700 font-mono text-xs">
                No files open
              </div>
            ) : activeTabData ? (
              <ScrollArea className="h-full">{activeTabData.content}</ScrollArea>
            ) : null}
          </div>
        </div>
      )}
    </div>
  );
}

